version: '3'
services:
  db:
    container_name: MYSQL
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    container_name: REDIS
    image: redis
    ports:
      - "6379:6379"
volumes:
  my-db: